import "./globals.css";
import { Work_Sans } from "next/font/google";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={workSans.className}>
      <body>
        <header className="min-h-[64px] px-8 flex items-center border-b border-b-slate-300">
          <h1 className="font-bold text-3xl">Canary</h1>
        </header>
        {children}
      </body>
    </html>
  );
}
